ALTER TABLE Users
DROP CONSTRAINT PK_CompositeIdUsername;

ALTER TABLE Users
ADD CONSTRAINT PK_Id
PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT Unique_Username 
UNIQUE(Username)

ALTER TABLE Users
ADD CONSTRAINT CHK_Users
CHECK (DATALENGTH(Username) >= 3)
